### ISSUE TITLE
missing "/" to close v-layout

### ISSUE THREAD

**Issue by lucassobfer** [abhaywawale/vuetipet#1]
could you please insert a "/" to close v-layout

https://github.com/abhaywawale/vuetipet/blob/90ed004a9e4f304e7a13d900e2361af63132073a/vuetipet-vscode/snippets/vuetify.json#L1377

thank you for this awesome snippet

**Comment by abhaywawale** [comment]
Got it.

**Comment by abhaywawale** [comment]
make sure you install new official extension
